### PR TITLE
Allow access to eighth sequence slot

### PR DESCRIPTION
**Pull request by tekktrik**
Addresses Issue #15 by opening up access to the eighth sequence slot.  Data sheet as posted by @caternuson does allow for this.

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by caternuson** [comment]
@tekktrik Did you test this? The 8th slot works as expected, etc.? Just wondering if original author ran into something weird that could explain why only 7 were being used.

(can't remember if i ever tested when writing issue)

**Comment by tekktrik** [comment]
@caternuson no not yet but was going to see if you had the hardware or otherwise I was going to pick it up.  My best guess is the datasheet got accidentally misinterprutted as saying that only 7 registers were used for sequences, when it's really the eight registers, which each use 7 of the **bits**.  The accompanying graphic in the datasheet regarding the registers made me think that anyway until I re-read it and realized.

**Comment by caternuson** [comment]
OK, I tested real quick. I had some DRV2605's I needed to repair anyway.

```python
Adafruit CircuitPython 7.1.0 on 2021-12-28; Adafruit QT Py RP2040 with rp2040
>>> import board
>>> import adafruit_drv2605
>>> drv = adafruit_drv2605.DRV2605(board.I2C())
>>> drv.sequence[0] = adafruit_drv2605.Pause(1)
>>> drv.sequence[1] = adafruit_drv2605.Effect(1)
>>> drv.sequence[2] = adafruit_drv2605.Pause(1)
>>> drv.sequence[3] = adafruit_drv2605.Effect(1)
>>> drv.sequence[4] = adafruit_drv2605.Pause(1)
>>> drv.sequence[5] = adafruit_drv2605.Effect(1)
>>> drv.sequence[6] = adafruit_drv2605.Pause(1)
>>> drv.sequence[7] = adafruit_drv2605.Effect(1)
>>> drv.play()
>>> 
```

I get the expected 4 rumbles with 1 sec pause between each. So seems to work. Looks good. Thanks for PR!

**Comment by tekktrik** [comment]
Hooray!  Thank you for the quick help!

**Pull request merged**
